name: slickcanvas_svg
version: 0.0.1
authors: SlickCanvas Authors
description: A flexible framework for HTML5 Canvas, SVG and WebGL.
homepage: http://www.slickcanvas.org
dependencies:
  slickcanvas_view:
    path: ../view