name: smartcanvas-example
version: 0.0.2
author: Kun Zhao <kzhdev@gmail.com>
homepage: http://www.smartcanvas.org
description: A SVG/Canvas framework for Dart.
dependencies:
  browser: '>=0.9.1 <0.9.2'
