name: smartcanvas
version: 0.0.1
author: Kun Zhao <kzhdev@gmail.com>
homepage: kzhdev.github.io/dart-smart-canvas
description: A SVG/Canvas framework for Dart.
dependencies:
  browser: '>=0.9.1 <0.9.2'
