name: smartcanvas
version: 0.1.9+1
authors: [Kun Zhao <kzhdev@gmail.com>]
description: A SVG/Canvas framework for Dart.
homepage: http://www.smartcanvas.org
dependencies:
  dart_ext: ">=0.0.12 <0.1.0"
  r2d2: ">=0.1.1 <0.2.0"
dev_dependencies:
  browser: any
  test: any
transformers:
- test/pub_serve:
    $include: test/test.dart, test/**_test{.*,}.dart
