name: slickcanvas_core
version: 0.0.1
authors: SlickCanvas Author(s)
description: A flexible framework for HTML5 Canvas, SVG and WebGL.
homepage: http://www.slickcanvas.org
dependencies:
  dart_ext: ">=0.0.12 <0.1.0"
  observable:
  uuid:
  svgpath:
