part of smartcanvas;

// canvas type
const String svg = 'svg';
const String canvas = 'canvas';

const String SPACE = ' ';
const String EMPTY = '';
const String COMMA = ',';

// events
const String MOUSEMOVE = 'mousemove';
const String MOUSEDOWN = 'mousedown';
const String MOUSEUP = 'mouseup';
const String MOUSEENTER = 'mouseenter';
const String MOUSELEAVE = 'mouseleave';
const String MOUSEOVER = 'mouseover';
const String MOUSEOUT = 'mouseout';
const String CLICK = 'click';
const String DBLCLICK = 'dblclick';
const String DRAGSTART = 'dragstart';
const String DRAGMOVE = 'dragmove';
const String DRAGEND = 'dragend';
const String CHANGED = 'Changed';
const String ATTR_CHANGED = '*Changed';

// attributes & styles
const String X = 'x';
const String Y = 'y';
const String WIDTH = 'width';
const String HEIGHT = 'height';
const String FILL = 'fill';
const String FILL_OPACITY = 'fill-opacity';
const String STROKE = 'stroke';
const String STROKE_WIDTH = 'stroke-width';
const String STROKE_OPACITY = 'stroke-opacity';
const String STROKE_LINECAP = 'stroke-linecap';
const String STROKE_DASHARRAY = 'stroke-dasharray';
const String STROKE_LINE_JOIN = 'stroke-linejoin';
const String OPACITY = 'opacity';
const String CX = 'cx';
const String CY = 'cy';
const String RX = 'rx';
const String RY = 'ry';
const String FX = 'fx';
const String FY = 'fy';
const String R = 'r';
const String FONT_SIZE = 'font-size';
const String FONT_FAMILY = 'font-family';
const String FONT_WEIGHT = 'font-weight';
const String FONT_STYLE = 'font-style';
const String NORMAL = 'normal';
const String BOLD = 'bold';
const String BOLDER = 'bolder';
const String LIGHTER = 'lighter';
const String ID = 'id';
const String CLASS = 'class';
const String STYLE = 'style';
const String SCALE = 'scale';
const String SCALE_X = 'scaleX';
const String SCALE_Y = 'scaleY';
const String TRANSFORM = 'transform';
const String DRAGGABLE = 'draggable';
const String TEXT = 'text';
const String PADDING = 'padding';
const String POINTS = 'points';
const String POSITION = 'position';
const String LEFT = 'left';
const String TOP = 'top';
const String MARGIN = 'margin';
const String D = 'd';
const String X1 = 'x1';
const String X2 = 'x2';
const String Y1 = 'y1';
const String Y2 = 'y2';
const String DISPLAY = 'display';
const String TEXT_ANCHOR = 'text-anchor';
const String ABSOLUTE = 'absolute';
const String ZERO = '0';
const String VIEWBOX = 'viewBox';
const String STAGE_MOUSE_DOWN = 'stageMouseDown';
const String STAGE_MOUSE_UP = 'stageMouseUp';
const String STAGE_MOUSE_MOVE = 'stageMouseMove';
const String STAGE_DBLCLICK = 'stageDblClick';
const String STAGE_CLICK = 'sstageClick';
const String OFFSET_X = 'offsetX';
const String OFFSET_Y = 'offsetY';
const String PATTERN_UNITS = 'patternUnits';
const String CREATE_SHADOW_ROOT = 'createShadowRoot';
const String STOPS = 'stops';
const String OFFSET = 'offset';
const String COLOR = 'color';
const String SPREAD_METHOD = 'spreadMethod';
const String DEF_ADDED = 'defAdded';
const String BACKGROUND = 'background';
const String IS_STATIC = 'isStatic';
const String HREF = 'href';
const String NS_XLINK = 'http://www.w3.org/1999/xlink';
const String ROTATE = 'rotate';
const String ROTATE_X = 'rotate_x';
const String ROTATE_Y = 'rotate_y';
const String NO_WRAP = 'nowrap';

// svg node names
const String SC_LAYER = '__sc_layer';
const String SC_GROUP = '__sc_group';
const String SC_TEXT = '__sc_text';
const String SC_RECT = '__sc_rect';
const String SC_POLYLINE = '__sc_polyline';
const String SC_POLYGON = '__sc_polygon';
const String SC_PATH = '__sc_path';
const String SC_LINE = '__sc_line';
const String SC_ELLIPSE = '__sc_ellipse';
const String SC_CIRCLE = '__sc_circle';
const String SC_PATTERN = '__sc_pattern';
const String SC_LINEAR_GRADIENT = '__sc_linear_gradient';
const String SC_RADIAL_GRADIENT = '__sc_radial_gradient';
const String SC_CANVAS = '__sc_canvas';
const String SC_IMAGE = '__sc_image';

// exception
const String ExpNotImplemented = 'Not Implemented';