part of smartcanvas;

const space = ' ';
const empty = '';
const comma = ',';

const normal = 'normal';
const bold = 'bold';
const bolder = 'bolder';
const lighter = 'lighter';

// events
const mouseMove = 'mousemove';
const mouseDown = 'mousedown';
const mouseUp = 'mouseup';
const mouseEnter = 'mouseenter';
const mouseLeave = 'mouseleave';
const mouseOver = 'mouseover';
const mouseOut = 'mouseout';
const click = 'click';
const dblClick = 'dblclick';
const dragStart = 'dragstart';
const dragMove = 'dragmove';
const dragEnd = 'dragend';
const changed = 'Changed';
const attrChanged = '*Changed';
const defAdded = 'defAdded';

const stageMouseDown = 'stageMouseDown';
const stageMouseUp = 'stageMouseUp';
const stageMouseMove = 'stageMouseMove';
const stageDblClick = 'stageDblClick';
const stageClick = 'stageClick';

// attributes & styles
const X = 'x';
const Y = 'y';
const WIDTH = 'width';
const HEIGHT = 'height';
const FILL = 'fill';
const FILL_OPACITY = 'fill-opacity';
const STROKE = 'stroke';
const STROKE_WIDTH = 'stroke-width';
const STROKE_OPACITY = 'stroke-opacity';
const STROKE_LINECAP = 'stroke-linecap';
const STROKE_DASHARRAY = 'stroke-dasharray';
const STROKE_LINE_JOIN = 'stroke-linejoin';
const OPACITY = 'opacity';
const CX = 'cx';
const CY = 'cy';
const RX = 'rx';
const RY = 'ry';
const FX = 'fx';
const FY = 'fy';
const R = 'r';
const FONT_SIZE = 'font-size';
const FONT_FAMILY = 'font-family';
const FONT_WEIGHT = 'font-weight';
const FONT_STYLE = 'font-style';
const ID = 'id';
const CLASS = 'class';
const STYLE = 'style';
const SCALE = 'scale';
const SCALE_X = 'scaleX';
const SCALE_Y = 'scaleY';
const TRANSFORM = 'transform';
const DRAGGABLE = 'draggable';
const TEXT = 'text';
const PADDING = 'padding';
const POINTS = 'points';
const POSITION = 'position';
const LEFT = 'left';
const TOP = 'top';
const MARGIN = 'margin';
const D = 'd';
const X1 = 'x1';
const X2 = 'x2';
const Y1 = 'y1';
const Y2 = 'y2';
const DISPLAY = 'display';
const TEXT_ANCHOR = 'text-anchor';
const ABSOLUTE = 'absolute';
const ZERO = '0';
const VIEWBOX = 'viewBox';
const OFFSET_X = 'offsetX';
const OFFSET_Y = 'offsetY';
const PATTERN_UNITS = 'patternUnits';
const CREATE_SHADOW_ROOT = 'createShadowRoot';
const STOPS = 'stops';
const OFFSET = 'offset';
const COLOR = 'color';
const SPREAD_METHOD = 'spreadMethod';
const BACKGROUND = 'background';
const IS_STATIC = 'isStatic';
const HREF = 'href';
const NS_XLINK = 'http://www.w3.org/1999/xlink';
const ROTATE = 'rotate';
const ROTATE_X = 'rotate_x';
const ROTATE_Y = 'rotate_y';
const NO_WRAP = 'nowrap';
const WORD_SPLITTER = 'wordSplitter';
const SHOW_CONTROLS = 'showControls';
const VISIBLE = 'visible';
const REFLECTABLE = 'reflectable';

// exception
const ExpNotImplemented = 'Not Implemented';
